spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
    tagsSorter: alpha